#!/usr/bin/env bash

# Package build output: AnyKernel3 flashable zip and, optionally, a boot image.

set -euo pipefail

# shellcheck source=scripts/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

KERNEL_DIR=${KERNEL_DIR:?KERNEL_DIR must be set}
WORKSPACE=${WORKSPACE:-$(cd "${KERNEL_DIR}/.." && pwd)}
ARCH=${ARCH:-arm64}
BOOT_OUT="${KERNEL_DIR}/out/arch/${ARCH}/boot"
AK3="${WORKSPACE}/AnyKernel3"

# ---------------------------------------------------------- AnyKernel3 ---

make_anykernel3() {
	group "Building AnyKernel3 package"

	rm -rf "$AK3"

	if is_true "${USE_CUSTOM_ANYKERNEL3:-false}"; then
		local src=${CUSTOM_ANYKERNEL3_SOURCE:?CUSTOM_ANYKERNEL3_SOURCE required}

		case "$src" in
			*.tar.gz|*.tgz)
				fetch "$src" "${WORKSPACE}/ak3.tar.gz"
				extract_archive "${WORKSPACE}/ak3.tar.gz" "$AK3"
				;;

			*.zip)
				fetch "$src" "${WORKSPACE}/ak3.zip"
				extract_archive "${WORKSPACE}/ak3.zip" "$AK3"
				;;

			*git*)
				retry 3 git clone -q --depth=1 \
					${CUSTOM_ANYKERNEL3_BRANCH:+-b "$CUSTOM_ANYKERNEL3_BRANCH"} \
					"$src" "$AK3" \
					|| die "failed to clone ${src}"
				;;

			*)
				fetch "$src" "${WORKSPACE}/ak3.zip"
				extract_archive "${WORKSPACE}/ak3.zip" "$AK3"
				;;
		esac
	else
		retry 3 git clone -q --depth=1 \
			https://github.com/osm0sis/AnyKernel3 \
			"$AK3" \
			|| die "failed to clone AnyKernel3"

		# Device checks are meaningless here: we do not know the target's
		# ro.product.device, and the zip is flashed deliberately by its builder.
		sed -i \
			's/do.devicecheck=1/do.devicecheck=0/g' \
			"${AK3}/anykernel.sh"

		sed -i \
			's!BLOCK=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!BLOCK=auto;!g' \
			"${AK3}/anykernel.sh"

		sed -i \
			's/IS_SLOT_DEVICE=0;/is_slot_device=auto;/g' \
			"${AK3}/anykernel.sh"
	fi

	local image_name="${KERNEL_IMAGE_NAME:-}"

	[ -n "$image_name" ] \
		|| die "KERNEL_IMAGE_NAME is not set"

	[ -f "${BOOT_OUT}/${image_name}" ] \
		|| die "kernel image missing at ${BOOT_OUT}/${image_name}"

	cp "${BOOT_OUT}/${image_name}" "${AK3}/" \
		|| die "failed to copy kernel image into AnyKernel3"

	if is_true "${CHECK_DTBO_IS_OK:-false}"; then
		[ -f "${BOOT_OUT}/dtbo.img" ] \
			|| die "CHECK_DTBO_IS_OK=true but ${BOOT_OUT}/dtbo.img is missing"

		cp "${BOOT_OUT}/dtbo.img" "${AK3}/" \
			|| die "failed to copy dtbo.img into AnyKernel3"
	fi

	rm -rf \
		"${AK3}/.git" \
		"${AK3}/.github" \
		"${AK3}/README.md"

	ok "AnyKernel3 package assembled"

	endgroup
}

# ---------------------------------------------------------- boot image ---

make_boot_image() {
	is_true "${BUILD_BOOT_IMG:-false}" || return 0

	group "Repacking boot image"

	local tools="${WORKSPACE}/tools"

	[ -x "${tools}/unpack_bootimg.py" ] ||
		[ -f "${tools}/unpack_bootimg.py" ] ||
		die "unpack_bootimg.py not found at ${tools}"

	[ -x "${tools}/mkbootimg.py" ] ||
		[ -f "${tools}/mkbootimg.py" ] ||
		die "mkbootimg.py not found at ${tools}"

	fetch \
		"${SOURCE_BOOT_IMAGE:?SOURCE_BOOT_IMAGE required}" \
		"${WORKSPACE}/boot-source.img"

	cd "$WORKSPACE"

	# Read the source boot image arguments generated by unpack_bootimg.py.
	#
	# IMPORTANT:
	# Do not pass "$fmt" directly to mkbootimg.py. The generated command
	# line contains quoted arguments such as the complete kernel cmdline.
	# Direct word splitting breaks --cmdline into multiple arguments.
	local fmt

	fmt=$(
		python3 "${tools}/unpack_bootimg.py" \
			--boot_img boot-source.img \
			--format mkbootimg
	) || die "failed to read the source boot image"

	info "source boot image args:"
	printf '%s\n' "$fmt" | sed 's/^/    /'

	# Unpack the boot image.
	python3 "${tools}/unpack_bootimg.py" \
		--boot_img boot-source.img \
		>/dev/null \
		|| die "failed to unpack the source boot image"

	# The unpacker creates the output directory used by mkbootimg.py.
	[ -d "${WORKSPACE}/out" ] \
		|| die "boot image unpack directory was not created"

	local image_name="${KERNEL_IMAGE_NAME:-}"

	[ -n "$image_name" ] \
		|| die "KERNEL_IMAGE_NAME is not set"

	[ -f "${BOOT_OUT}/${image_name}" ] \
		|| die "kernel image missing at ${BOOT_OUT}/${image_name}"

	# Replace the original kernel with the newly compiled kernel.
	[ -d "${WORKSPACE}/out" ] \
		|| die "unpacked boot output directory missing: ${WORKSPACE}/out"

	cp "${BOOT_OUT}/${image_name}" \
		"${WORKSPACE}/out/kernel" \
		|| die "could not stage the new kernel into the unpacked ramdisk"

	# -------------------------------------------------------------
	# Preserve the argument boundaries generated by unpack_bootimg.py.
	#
	# Example:
	#   --cmdline 'androidboot.hardware=qcom ... swiotlb=2048'
	#
	# must remain ONE --cmdline argument.
	#
	# eval is intentional here because unpack_bootimg.py emits a
	# shell-quoted mkbootimg command line.
	# -------------------------------------------------------------
	local -a boot_args

	eval "boot_args=( $fmt )"

	[ "${#boot_args[@]}" -gt 0 ] \
		|| die "mkbootimg argument list is empty"

	info "rebuilding boot image"

	python3 "${tools}/mkbootimg.py" \
		"${boot_args[@]}" \
		-o "${WORKSPACE}/boot.img" \
		|| die "mkbootimg failed"

	[ -s "${WORKSPACE}/boot.img" ] \
		|| die "boot.img was not produced"

	ok "boot.img built ($(du -h "${WORKSPACE}/boot.img" | cut -f1))"

	export_env MAKE_BOOT_IMAGE_IS_OK true

	endgroup
}

# ------------------------------------------------------------- summary ---

write_summary() {
	summary ""
	summary "### Build artifacts"
	summary ""
	summary "| Artifact | Size |"
	summary "| --- | --- |"

	local f

	for f in \
		"${BOOT_OUT}/${KERNEL_IMAGE_NAME:-}" \
		"${BOOT_OUT}/dtbo.img" \
		"${WORKSPACE}/boot.img"
	do
		if [ -n "$f" ] && [ -f "$f" ]; then
			summary "| \`$(basename "$f")\` | $(du -h "$f" | cut -f1) |"
		fi
	done

	if [ -d "$AK3" ]; then
		summary "| \`AnyKernel3\` (flashable package) | $(du -sh "$AK3" | cut -f1) |"
	fi

	summary ""
}

# --------------------------------------------------------------- main ---

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
	case "${1:-all}" in

		anykernel3)
			make_anykernel3
			;;

		bootimg)
			make_boot_image
			;;

		all)
			make_anykernel3
			make_boot_image
			write_summary
			;;

		*)
			die "unknown package step '$1'"
			;;

	esac
fi
